version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    env_file: ./app/.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn bmatrix.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./app:/app
    ports:
      - "8883:8000"
    depends_on:
      - db
    env_file:
      - ./app/.env

volumes:
  pgdata:
