version: '3.8'

services:
  web:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - ./app:/app
      - static_volume:/app/static
      - media_volume:/app/media
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn bmatrix.wsgi:application --bind 0.0.0.0:8000"

  shop.bountymatrix.net:
    image: nginx:1.21
    container_name: shop.bountymatrix.net
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webroot:/var/www/html
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webroot:/var/www/html
    depends_on:
      - shop.bountymatrix.net
    command: certonly --webroot --webroot-path=/var/www/html --email admin@bountymatrix.net --agree-tos --no-eff-email --staging -d shop.bountymatrix.net
    # Sau khi đã kiểm tra thành công, xóa --staging để lấy chứng chỉ chính thức

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: Shopsothutu123@
      POSTGRES_DB: shopbountymatrix
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7
    restart: always
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
  certbot-etc:
  certbot-var:
  webroot: 