# Generated by Django 5.2.3 on 2025-06-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_brand_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('in_stock', 'Còn hàng'), ('out_of_stock', 'Hết hàng'), ('pre_order', 'Đặt trước'), ('discontinued', 'Ngừng kinh doanh'), ('coming_soon', 'Sắp có hàng')], default='in_stock', max_length=20),
        ),
    ]
